
- name: Configure Application
  hosts: app_servers
  become: true
  tasks:
    - name: Install required packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - mysql

    - name: Copy application configuration
      copy:
        src: config/app.conf
        dest: /etc/app.conf
      notify:
        - Restart Application

  handlers:
    - name: Restart Application
      service:
        name: httpd
        state: restarted
